"""Поля обложек для Мест и Маршрутов

Revision ID: ab218e4d928a
Revises: 27901f73e9f2
Create Date: 2024-12-04 19:05:35.981567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ab218e4d928a'
down_revision: Union[str, None] = '27901f73e9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('photo', sa.String(), nullable=True))
    op.add_column('routes', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'photo')
    op.drop_column('places', 'photo')
    # ### end Alembic commands ###
