services:
  web:
    build:
      context: .
    container_name: travelcraft_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
      - ./media:/app/media
    env_file:
      - .env
    command: >
      bash -c "alembic upgrade head &&
               uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: travelcraft_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:

